### ISSUE TITLE
Unknown command pubrunner

### ISSUE THREAD

**Issue by iCHAIT** [jakelever/pubrunner#6]
Hi Jake,

As discussed in [another thread](https://github.com/jakelever/biowordlists/issues/1), I am trying to run your [biowordlists](https://github.com/jakelever/biowordlists) project to create the latest Term List. I was able to successfully install `pubrunner` via `pip`.

However, when I try to run it I get the following error - 

```shell
fish: Unknown command pubrunner
```

FYI, I am using the [fish shell](https://fishshell.com/), I don't think that should make a difference since I even tried to run it with bash but got the same error.

I am using Python 3.7. I thought it may be an issue of PATH so I tried to debug a bit but everything looks fine.

Ran the following command to see the installed location of `pubrunner` - 

```shell
$ pip3 show pubrunner

Name: pubrunner
Version: 0.5.2
Summary: A framework to rerun text mining tools on the latest publications
Home-page: http://github.com/jakelever/pubrunner
Author: Jake Lever
Author-email: jake.lever@gmail.com
License: MIT
Location: /Users/chaitanyagupta/Library/Python/3.7/lib/python/site-packages
Requires: future, wget, six, gitpython, drmaa, bioc, snakemake, markdown2, pyfiglet, biopython, jsonlines, pymarc, ftputil, pyyaml, requests
Required-by:
```

I also checked my sys.path to see if it had the above location `/Users/chaitanyagupta/Library/Python/3.7/lib/python/site-packages`, and it is present - 

```shell
$python3

Python 3.7.3 (default, Mar 27 2019, 09:23:15)
[Clang 10.0.1 (clang-1001.0.46.3)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import sys
>>> print(sys.path)
['', '/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python37.zip', '/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7', '/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/lib-dynload', '/Users/chaitanyagupta/Library/Python/3.7/lib/python/site-packages', '/usr/local/lib/python3.7/site-packages']
```

Can you help me with this? I am not sure what I can do to get it running.

Edit: Included link to the other thread

**Comment by jakelever** [comment]
I just tried it using a [Docker image](https://github.com/dideler/docker-fish-shell) for the fish shell and didn't have any issues getting it running. Are you able to use virtualenv?

**Comment by iCHAIT** [comment]
I tried using virtualenv on my work PC, but it didn't work. I just tried on another machine using pip and it doesn't work on it either and gave me the same error, however, I was able to get it running using virtualenv. Closing this issue, as it seems something fishy may be going on with my work machine.
